spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "docker"
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true